defmodule ExBlog.Agent.Skills.EditorialTest do
  use ExBlog.DataCase, async: false

  alias ExBlog.Agent
  alias ExBlog.Telegram.Image
  alias Spectre.Beam.Content
  alias Spectre.Beam.Inbound
  alias Spectre.Result

  test "the nested creation flow collects generation choices and stages a Kinetic action" do
    conversation_id = conversation_id()

    assert {:ok, started} = ask("/create", conversation_id)
    assert started.route.label == :START_ARTICLE_CREATION
    assert started.route.scope == {:skill, :editorial}
    assert started.state.current_flow == :article_brief
    assert started.state.current_scope == {:skill, :editorial}

    assert {:ok, briefed} =
             ask(
               "Spiega flow annidati, skill e policy con esempi pratici.",
               conversation_id
             )

    assert briefed.route.label == :CAPTURE_ARTICLE_BRIEF
    assert briefed.route.strategy == :creation_continuation
    assert briefed.state.current_flow == :article_language

    assert {:ok, localized} = ask("it", conversation_id)
    assert localized.route.label == :CAPTURE_ARTICLE_LANGUAGE
    assert localized.state.current_flow == :article_category

    assert {:ok, categorized} = ask("Elixir", conversation_id)
    assert categorized.route.label == :CAPTURE_ARTICLE_CATEGORY
    assert categorized.state.current_flow == :article_title

    assert {:ok, titled} = ask("Phoenix e Spectre", conversation_id)
    assert titled.route.label == :CAPTURE_ARTICLE_TITLE
    assert titled.state.current_flow == :article_seo

    assert {:ok, staged} = ask("genera SEO", conversation_id)

    assert staged.route.label == :CAPTURE_ARTICLE_SEO
    assert staged.state.current_flow == nil
    assert staged.state.current_scope == nil
    refute Map.has_key?(staged.state.data, :article_creation)

    effect = Result.pending_effect(staged)
    assert effect.name == :create_article
    assert effect.owner == ExBlog.Agent.Skills.Editorial
    assert effect.scope == {:skill, :editorial}
    assert effect.status == :waiting_policy
    assert effect.policy == {{:skill, :editorial}, :editorial_confirmation}

    assert effect.args == %{
             "title" => "Phoenix e Spectre",
             "category" => "Elixir",
             "lang" => "it",
             "brief" => "Spiega flow annidati, skill e policy con esempi pratici.",
             "generate_seo" => true,
             "cover" => "",
             "cover_alt" => ""
           }

    awaitable = Result.open_awaitable(staged)
    assert awaitable.name == {{:skill, :editorial}, :editorial_confirmation}
    assert staged.reply_text =~ "Titolo: Phoenix e Spectre"
    assert staged.reply_text =~ "SEO e tag: generati con OpenRouter"
  end

  test "category and title can be generated by OpenRouter inside their nested flows" do
    conversation_id = conversation_id()

    assert {:ok, _started} = ask("/create", conversation_id)
    assert {:ok, _briefed} = ask("Una guida pratica ai flow Spectre.", conversation_id)
    assert {:ok, _localized} = ask("it", conversation_id)
    test_pid = self()

    category_ai = fn :fast, prompt, opts ->
      send(test_pid, {:category_prompt, prompt, opts})
      {:ok, %{text: "Intelligenza artificiale"}}
    end

    assert {:ok, categorized} =
             ask("genera categoria", conversation_id, ai_complete: category_ai)

    assert categorized.state.current_flow == :article_title
    assert_received {:category_prompt, category_prompt, category_opts}
    assert category_prompt =~ "Una guida pratica ai flow Spectre."
    assert category_opts[:purpose] == :category_generation

    title_ai = fn :balanced, prompt, opts ->
      send(test_pid, {:title_prompt, prompt, opts})
      {:ok, %{text: ~s("Flow Spectre per redazioni affidabili")}}
    end

    assert {:ok, titled} = ask("genera titolo", conversation_id, ai_complete: title_ai)
    assert titled.state.current_flow == :article_seo
    assert titled.reply_text =~ "Flow Spectre per redazioni affidabili"
    assert titled.reply_text =~ "generato con OpenRouter"
    assert_received {:title_prompt, title_prompt, title_opts}
    assert title_prompt =~ "Intelligenza artificiale"
    assert title_opts[:purpose] == :title_generation

    assert {:ok, staged} = ask("salta", conversation_id)
    assert Result.pending_effect(staged).args["generate_seo"] == false
  end

  test "an authenticated Telegram photo is saved without advancing the active flow" do
    conversation_id = conversation_id()
    root = temporary_directory()
    bytes = <<0xFF, 0xD8, 0xFF, 0xE0, "telegram-cover">>
    on_exit(fn -> File.rm_rf!(root) end)

    assert {:ok, _started} = ask("/create", conversation_id)
    assert {:ok, input} = Image.prepare(image_inbound(conversation_id, byte_size(bytes)))

    downloader = fn _session_id, {:file_id, 77}, _opts -> {:ok, %{bytes: bytes}} end

    assert {:ok, attached} =
             ask(input, conversation_id,
               telegram_media_downloader: downloader,
               article_asset_root: root
             )

    assert attached.route.label == :ATTACH_ARTICLE_IMAGE
    assert attached.state.current_flow == :article_brief
    workflow = attached.state.data.article_creation
    assert workflow.cover_alt == "Schema Spectre e Kinetic"
    assert workflow.cover =~ "/images/articles/"
    assert attached.reply_text =~ workflow.cover
    assert [_stored] = File.ls!(root)
  end

  test "an invalid language keeps the administrator inside the language flow" do
    conversation_id = conversation_id()

    assert {:ok, _started} = ask("/create", conversation_id)
    assert {:ok, _briefed} = ask("Brief completo", conversation_id)
    assert {:ok, result} = ask("fr", conversation_id)

    assert result.route.label == :CAPTURE_ARTICLE_LANGUAGE
    assert result.state.current_flow == :article_language
    assert result.reply_text =~ "Valori ammessi: it, en"
  end

  test "the global cancel interrupt clears an active creation flow" do
    conversation_id = conversation_id()

    assert {:ok, _started} = ask("/create", conversation_id)
    assert {:ok, _briefed} = ask("Brief da scartare", conversation_id)
    assert {:ok, cancelled} = ask("/cancel", conversation_id)

    assert cancelled.route.label == :CANCEL_ARTICLE_CREATION
    assert cancelled.state.current_flow == nil
    assert cancelled.state.current_scope == nil
    refute Map.has_key?(cancelled.state.data, :article_creation)
    assert cancelled.reply_text =~ "annullata"
  end

  defp ask(message, conversation_id, opts \\ []) do
    Spectre.ask(Agent, message, Keyword.put(opts, :conversation_id, conversation_id))
  end

  defp image_inbound(conversation_id, size) do
    %Inbound{
      endpoint: :telegram,
      channel_type: :telegram,
      message_id: "image-77",
      conversation_id: conversation_id,
      sender: ExBlog.Config.get().admin_telegram_id,
      content: %Content{
        type: :image,
        text: "Schema Spectre e Kinetic",
        data: %{file_id: 77, size: size},
        metadata: %{}
      },
      authenticated?: true,
      metadata: %{}
    }
  end

  defp temporary_directory do
    path =
      Path.join(
        System.tmp_dir!(),
        "ex-blog-editorial-assets-#{System.unique_integer([:positive, :monotonic])}"
      )

    File.mkdir_p!(path)
    path
  end

  defp conversation_id do
    "editorial-skill-#{System.unique_integer([:positive, :monotonic])}"
  end
end
