# Gettext generates the plural dispatch inside the backend module and hands
# Expo's opaque %Expo.PluralForms{} straight to Gettext.Plural.plural/2.
# Dialyzer reports the opaqueness violation against our module even though the
# code is generated by the library.
[
  {"lib/ex_blog_web/gettext.ex", :call_without_opaque}
]
