defmodule ExBlogWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ex_blog

  # Browser sessions are signed and encrypted. Production cookies are sent
  # only over HTTPS; development keeps HTTP support on the loopback interface.
  @session_options [
    store: :cookie,
    key: "_ex_blog_key",
    signing_salt: "jJyZOVU/",
    encryption_salt: "Lz1DVLX7FfQ7y0nM",
    http_only: true,
    secure: Application.compile_env(:ex_blog, :secure_session_cookie?, true),
    same_site: "Strict",
    max_age: 8 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ex_blog,
    gzip: not code_reloading?,
    only: ExBlogWeb.static_paths(),
    only_matching: ["favicon-"],
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug CORSPlug,
    origin: &__MODULE__.cors_origins/0,
    credentials: true

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ExBlogWeb.Router

  @doc false
  def cors_origins do
    Application.get_env(:ex_blog, :cors_origins, [])
  end
end
