import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ex_blog, ExBlogWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :ex_blog, ExBlogWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Production uses the budgeted OpenRouter embedding boundary. Development
# classifier artifacts are 384-dimensional and must never be loaded beside the
# hosted 1,024-dimensional semantic-cache vectors.
config :ex_blog, :spectre_embedding_adapter, ExBlog.AI.Embedding

config :spectre, :classifier,
  artifact_dir: nil,
  embedding_adapter: ExBlog.Agent.Embedding,
  local_classifier_enabled?: false,
  required?: false,
  start?: false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
